### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ethercrow** [RLovelett/langserver-swift#28]
```
~/s/langserver-swift (master|✓)
$ make debug
swift build -Xswiftc -target -Xswiftc x86_64-apple-macosx10.11
Updating https://github.com/thoughtbot/Argo.git
Updating https://github.com/RLovelett/SourceKit.git
Updating https://github.com/thoughtbot/Curry.git
Updating https://github.com/RLovelett/swift-package-manager.git
Updating https://github.com/edwardaux/Ogra.git
Updating https://github.com/thoughtbot/Runes.git
error: noManifest(baseURL: "https://github.com/thoughtbot/Argo.git", version: Optional("4.0.0"))
make: *** [debug] Error 1
Exit code: 2
$ swift --version
Apple Swift version 4.0 (swiftlang-900.0.59 clang-900.0.34.2)
Target: x86_64-apple-macosx10.9
```

**Comment by RLovelett** [comment]
There is no support for Swift 4 yet.

**Comment by RLovelett** [comment]
This should now be fixed on master.

**Comment by ethercrow** [comment]
Thank you!

**Comment by jancassio** [comment]
Hi guys,

I tried to build using the instructions of release page, then, I got the same problem reported here.

Building from master branch, the build still getting erros, but a diferent one

```
wift build -Xswiftc -static-stdlib -Xswiftc -target -Xswiftc x86_64-apple-macosx10.11 -c release
Fetching https://github.com/RLovelett/Argo.git
Fetching https://github.com/drmohundro/SWXMLHash.git
Fetching https://github.com/RLovelett/Ogra.git
Updating https://github.com/RLovelett/swift-package-manager.git
Updating https://github.com/thoughtbot/Curry.git
Updating https://github.com/thoughtbot/Runes.git
Updating https://github.com/RLovelett/SourceKit.git
Cloning https://github.com/RLovelett/SourceKit.git
Resolving https://github.com/RLovelett/SourceKit.git at 1.0.2
Cloning https://github.com/RLovelett/swift-package-manager.git
Resolving https://github.com/RLovelett/swift-package-manager.git at swift-4.1-branch
Cloning https://github.com/thoughtbot/Curry.git
Resolving https://github.com/thoughtbot/Curry.git at 4.0.1
Cloning https://github.com/thoughtbot/Runes.git
Resolving https://github.com/thoughtbot/Runes.git at 4.1.1
Cloning https://github.com/RLovelett/Argo.git
Resolving https://github.com/RLovelett/Argo.git at swift-4.1-macOS-and-linux
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 4.7.0
Cloning https://github.com/RLovelett/Ogra.git
Resolving https://github.com/RLovelett/Ogra.git at master
Compile clibc libc.c
Compile Swift Module 'PackageDescription' (6 sources)
Compile Swift Module 'PackageDescription4' (9 sources)
Compile Swift Module 'Runes' (9 sources)
Compile Swift Module 'SWXMLHash' (3 sources)
Compile Swift Module 'Curry' (1 sources)
Compile Swift Module 'Argo' (17 sources)
Compile Swift Module 'libc' (1 sources)
Compile Swift Module 'POSIX' (11 sources)
Compile Swift Module 'SourceKitter' (11 sources)
Compile Swift Module 'Ogra' (1 sources)
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:17:19: error: 'init(subsystem:category:)' is only available on OS X 10.12 or newer
private let log = OSLog(subsystem: "me.lovelett.langserver-swift", category: "SourceKit")
                  ^
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:98:13: error: 'os_log(_:dso:log:type:_:)' is only available on OS X 10.12 or newer
            os_log("%{public}@", log: log, type: .default, description)
            ^
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:98:13: note: add 'if #available' version check
            os_log("%{public}@", log: log, type: .default, description)
            ^
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:92:17: note: add @available attribute to enclosing instance method
    public func request() -> Decoded<JSON> {
                ^
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:21:20: note: add @available attribute to enclosing class
public final class SourceKit {
                   ^
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:98:51: error: 'default' is only available on OS X 10.12 or newer
            os_log("%{public}@", log: log, type: .default, description)
                                                  ^
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:98:51: note: add 'if #available' version check
            os_log("%{public}@", log: log, type: .default, description)
                                                  ^
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:92:17: note: add @available attribute to enclosing instance method
    public func request() -> Decoded<JSON> {
                ^
/Users/terced-janio/Works/labs/swift/langserver-swift/Sources/SourceKitter/Types/SourceKit.swift:21:20: note: add @available attribute to enclosing class
public final class SourceKit {
                   ^
error: terminated(1): /Library/Developer/CommandLineTools/usr/bin/swift-build-tool -f /Users/terced-janio/Works/labs/swift/langserver-swift/.build/release.yaml main output:
```
